package CLOSEST_INTEGER;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class ClosestIntegerTest {


    // should return the closest integer for positive integer values
    @Test
    public void test_positive_integer() {
        int result = CLOSEST_INTEGER.closest_integer("10");
        assertEquals(10, result);
    }

    // should return the closest integer for the maximum integer value
    @Test
    public void test_maximum_integer() {
        int result = CLOSEST_INTEGER.closest_integer(String.valueOf(Integer.MAX_VALUE));
        assertEquals(Integer.MAX_VALUE, result);
    }

    // should return the closest integer for the minimum integer value
    @Test
    public void test_minimum_integer_value() {
        int result = CLOSEST_INTEGER.closest_integer(Integer.toString(Integer.MIN_VALUE));
        assertEquals(Integer.MIN_VALUE, result);
    }
}