package DIGITS;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class DIGITSTest {


    // Returns the product of the odd digits of a positive integer.
    @Test
    public void test_product_of_odd_digits() {
        int result = DIGITS.digits(235);
        assertEquals(15, result);
    }

    // Returns 0 if the input is 0.
    @Test
    public void test_zero_input() {
        int result = DIGITS.digits(0);
        assertEquals(0, result);
    }

    // Returns 0 if the input is a negative integer.
    @Test
    public void test_negative_integer_input() {
        int result = DIGITS.digits(-235);
        assertEquals(0, result);
    }
}