package ADD;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class ADDTest {


    // Adding two positive integers returns their sum
    @Test
    public void test_add_positive_integers() {
        int result = ADD.add(2, 3);
        assertEquals(5, result);
    }

    // Adding the maximum integer and 1 throws an ArithmeticException
    @Test
    public void test_add_maximum_integer_and_1() {
        assertThrows(ArithmeticException.class, () -> ADD.add(Integer.MAX_VALUE, 1));
    }

    // Adding the minimum integer and -1 throws an ArithmeticException
    @Test
    public void test_add_minimum_integer_and_minus_one_throws_exception() {
        assertThrows(ArithmeticException.class, () -> {
            ADD.add(Integer.MIN_VALUE, -1);
        });
    }
}