package BELOW_THRESHOLD;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class BelowThresholdTest {


    // Returns True if all numbers in the list are below the threshold
    @Test
    public void test_all_numbers_below_threshold() {
        int[] l = {1, 2, 4, 10};
        int t = 100;
        boolean result = BELOW_THRESHOLD.below_threshold(l, t);
        assertTrue(result);
    }

    // Returns False if all elements in the list are equal to the threshold
    @Test
    public void test_all_elements_equal_to_threshold() {
        int[] l = {1, 20, 4, 10};
        int t = 5;
        boolean result = BELOW_THRESHOLD.below_threshold(l, t);
        assertFalse(result);
    }

    // Returns True if all elements in the list are below the threshold except for one that is equal to the threshold
    @Test
    public void test_all_numbers_below_threshold_except_one() {
        int[] l = {1, 2, 4, 10, 100};
        int t = 100;
        boolean result = BELOW_THRESHOLD.below_threshold(l, t);
        assertFalse(result);
    }
}