package BF;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.Arrays;

public class BFTest {


    // Should return a list of planets between two given planets
    @Test
    public void test_planets_between_two_given_planets() {
        ArrayList<String> expected = new ArrayList<String>(Arrays.asList("Saturn", "Uranus"));
        ArrayList<String> result = BF.bf("Jupiter", "Neptune");
        assertEquals(expected, result);
    
        expected = new ArrayList<String>(Arrays.asList("Venus"));
        result = BF.bf("Earth", "Mercury");
        assertEquals(expected, result);
    
        expected = new ArrayList<String>(Arrays.asList("Venus", "Earth", "Mars", "Jupiter", "Saturn"));
        result = BF.bf("Mercury", "Uranus");
        assertEquals(expected, result);
    }

    // Should return an empty list if both planets are the same and not in the list of planets
    @Test
    public void test_empty_list_if_same_planet_not_in_list() {
        ArrayList<String> expected = new ArrayList<String>();
        ArrayList<String> result = BF.bf("Pluto", "Pluto");
        assertEquals(expected, result);
    
        result = BF.bf("Earth", "Earth");
        assertEquals(expected, result);
    }

    // Should return an empty list if either planet is not in the list of planets and the other is
    @Test
    public void test_empty_list_if_planet_not_in_list() {
        ArrayList<String> expected = new ArrayList<String>();
        ArrayList<String> result = BF.bf("Pluto", "Earth");
        assertEquals(expected, result);

        expected = new ArrayList<String>();
        result = BF.bf("Mars", "Pluto");
        assertEquals(expected, result);

        expected = new ArrayList<String>();
        result = BF.bf("Pluto", "Pluto");
        assertEquals(expected, result);
    }
}