package DOUBLE_THE_DIFFERENCE;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class DoubleTheDifferenceTest {


    // Returns 0 when given an empty list
    @Test
    public void test_empty_list() {
        double[] lst = {};
        int result = DOUBLE_THE_DIFFERENCE.double_the_difference(lst);
        assertEquals(0, result);
    }

    // Returns 0 when given a list containing only 0
    @Test
    public void test_list_with_only_zero() {
        double[] lst = {0};
        int result = DOUBLE_THE_DIFFERENCE.double_the_difference(lst);
        assertEquals(0, result);
    }

    // Returns the correct result when given a list containing only 1
    @Test
    public void test_behaviour_when_given_list_containing_only_1() {
        double[] lst = {1};
        int result = DOUBLE_THE_DIFFERENCE.double_the_difference(lst);
        assertEquals(1, result);
    }
}