package FACTORIZE;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.List;

public class FACTORIZETest {


    // Returns an empty list when given number is 1
    @Test
    public void test_returns_empty_list_when_given_number_is_1() {
        List<Integer> result = FACTORIZE.factorize(1);
        assertTrue(result.isEmpty());
    }

    // Returns correct factors when given number is the maximum integer value
    @Test
    public void test_returns_correct_factors_when_given_number_is_maximum_integer_value() {
        List<Integer> result = FACTORIZE.factorize(Integer.MAX_VALUE);
        List<Integer> expected = new ArrayList<>();
        expected.add(Integer.MAX_VALUE);
        assertEquals(expected, result);
    }

    // Returns correct factors when given number is the minimum integer value
    @Test
    public void test_returns_correct_factors_when_given_number_is_minimum_integer_value() {
        List<Integer> result = FACTORIZE.factorize(Integer.MIN_VALUE);
        assertEquals(2, result.size());
        assertEquals(-1, (int)result.get(0));
        assertEquals(1073741827, (int)result.get(1));
    }
}