package EVEN_ODD_PALINDROME;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.Arrays;

public class EvenOddPalindromeTest {


    // Returns correct tuple for input n=1
    @Test
    public void test_returns_correct_tuple_for_input_n_1() {
        ArrayList<Integer> expected = new ArrayList<>(Arrays.asList(0, 1));
        ArrayList<Integer> result = EVEN_ODD_PALINDROME.even_odd_palindrome(1);
        assertEquals(expected, result);
    }

    // Returns (0, 0) for input n=0
    @Test
    public void test_returns_0_0_for_input_n_0() {
        ArrayList<Integer> expected = new ArrayList<>(Arrays.asList(0, 0));
        ArrayList<Integer> result = EVEN_ODD_PALINDROME.even_odd_palindrome(0);
        assertEquals(expected, result);
    }

    // Returns (0, 0) for input n=-1
    @Test
    public void test_returns_correct_tuple_for_input_n_minus_1() {
        ArrayList<Integer> expected = new ArrayList<>(Arrays.asList(0, 0));
        ArrayList<Integer> result = EVEN_ODD_PALINDROME.even_odd_palindrome(-1);
        assertEquals(expected, result);
    }
}