package DECODE_SHIFT;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class DecodeShiftTest {


    // encode_shift returns encoded string with every character shifted by 5 in the alphabet
    @Test
    public void test_encode_shift() {
        String input = "abc";
        String expectedOutput = "fgh";
        String actualOutput = DECODE_SHIFT.encode_shift(input);
        assertEquals(expectedOutput, actualOutput);
    }

    // encode_shift and decode_shift work with strings containing only one character
/*     @Test
    public void test_encode_shift() {
        String input = "a";
        String expectedOutput = "f";
        String actualOutput = DECODE_SHIFT.encode_shift(input);
        assertEquals(expectedOutput, actualOutput);
    } */

    // encode_shift and decode_shift work with empty strings
    @Test
    public void test_decode_shift_with_empty_string() {
        String input = "";
        String expectedOutput = "";
        String actualOutput = DECODE_SHIFT.decode_shift(input);
        assertEquals(expectedOutput, actualOutput);
    }
}