package COMPARE;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class COMPARETest {


    // The method returns an array of the same length as the input arrays.
    @Test
    public void test_returns_array_of_same_length() {
        int[] game = {1, 2, 3};
        int[] guess = {4, 5, 6};
        int[] expected = {3, 3, 3};
    
        int[] result = COMPARE.compare(game, guess);
    
        assertEquals(expected.length, result.length);
    }

    // The method returns an empty array when the input arrays are empty.
    @Test
    public void test_returns_empty_array_when_input_arrays_are_empty() {
        int[] game = {};
        int[] guess = {};
        int[] expected = {};
    
        int[] result = COMPARE.compare(game, guess);
    
        assertArrayEquals(expected, result);
    }

    // The method throws an exception when the input arrays have different lengths.
    @Test
    public void test_throws_exception_when_input_arrays_have_different_lengths() {
        int[] game = {1, 2, 3};
        int[] guess = {4, 5};

        assertThrows(IllegalArgumentException.class, () -> COMPARE.compare(game, guess));
    }
}