package CHANGE_BASE;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class ChangeBaseTest {


    // Should return '0' when x is 0 and base is any number less than 10
    @Test
    public void test_zero_input() {
        String result = CHANGE_BASE.change_base(0, 5);
        assertEquals("0", result);
    }

    // Should return an empty string when x is negative and base is any number less than 10
    @Test
    public void test_negative_input() {
        String result = CHANGE_BASE.change_base(-7, 3);
        assertEquals("", result);
    }

    // Should return an empty string when base is negative and x is any number less than 10
    @Test
    public void test_base_negative_and_x_less_than_10() {
        String result = CHANGE_BASE.change_base(1, -5);
        assertEquals("", result);

        result = CHANGE_BASE.change_base(5, -2);
        assertEquals("", result);

        result = CHANGE_BASE.change_base(9, -8);
        assertEquals("", result);
    }
}