package COUNT_UPPER;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class CountUpperTest {


    // Should return 0 when given an empty string
    @Test
    public void test_empty_string() {
        int result = COUNT_UPPER.count_upper("");
        assertEquals(0, result);
    }

    // Should handle strings with only one character
    @Test
    public void test_single_character() {
        int result = COUNT_UPPER.count_upper("A");
        assertEquals(0, result);
    }

    // Should handle strings with only two characters
    @Test
    public void test_behaviour_two_characters() {
        int result1 = COUNT_UPPER.count_upper("AB");
        assertEquals(1, result1);

        int result2 = COUNT_UPPER.count_upper("ab");
        assertEquals(0, result2);

        int result3 = COUNT_UPPER.count_upper("aB");
        assertEquals(0, result3);

        int result4 = COUNT_UPPER.count_upper("Ab");
        assertEquals(1, result4);
    }
}