package DO_ALGEBRA;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

import javax.script.ScriptException;

public class DoAlgebraTest {


    // Test with two operands and one operator
    @Test
    public void test_two_operands_one_operator() throws ScriptException {
        String[] operator = {"+"};
        int[] operand = {2, 3};
        double expected = 5.0;
        double result = DO_ALGEBRA.do_algebra(operator, operand);
        assertEquals(expected, result, 0.0001);
    }

    // Test with empty operator list
    @Test
    public void test_empty_operator_list() throws ScriptException {
        String[] operator = {};
        int[] operand = {2, 3};
        double expected = 2.0;
        double result = DO_ALGEBRA.do_algebra(operator, operand);
        assertEquals(expected, result, 0.0001);
    }

    // Test with empty operand list
    @Test
    public void test_empty_operand_list() throws ScriptException {
        String[] operator = {"+"};
        int[] operand = {};
        assertThrows(ArrayIndexOutOfBoundsException.class, () -> {
            DO_ALGEBRA.do_algebra(operator, operand);
        });
    }
}