package FIB;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class FIBTest {


    // Returns the correct Fibonacci number for n=0
    @Test
    public void test_correct_fibonacci_number_for_n_0() {
        int result = FIB.fib(0);
        assertEquals(0, result);
    }

    // Returns 0 for n=0
    @Test
    public void test_returns_0_for_n_0() {
        int result = FIB.fib(0);
        assertEquals(0, result);
    }

    // Returns 1 for n=1
    @Test
    public void test_returns_1_for_n_1() {
        int result = FIB.fib(1);
        assertEquals(1, result);
    }
}