package BELOW_ZERO;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class BelowZeroTest {


    // The method returns false if the input list is empty.
    @Test
    public void test_empty_list_returns_false() {
        List<Integer> operations = new ArrayList<>();
        boolean result = BELOW_ZERO.below_zero(operations);
        assertFalse(result);
    }

    // The method returns true if the input list contains a single negative integer.
    @Test
    public void test_single_negative_integer_returns_true() {
        List<Integer> operations = new ArrayList<>();
        operations.add(-5);
        boolean result = BELOW_ZERO.below_zero(operations);
        assertTrue(result);
    }

    // The method returns true if the input list contains multiple negative integers followed by a positive integer.
    @Test
    public void test_multiple_negative_followed_by_positive() {
        List<Integer> operations = Arrays.asList(-1, -2, 3);
        boolean result = BELOW_ZERO.below_zero(operations);
        assertTrue(result);
    }
}