package FILE_NAME_CHECK;

// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class FILENAMECHECKTest {

    // Returns 'Yes' for a valid file name with one dot and no more than three digits.
    @Test
    public void test_valid_file_name() {
        String result = FILE_NAME_CHECK.file_name_check("example.txt");
        assertEquals("Yes", result);
    }

    // Returns 'No' for a file name with a substring before the dot that starts with a digit.
    @Test
    public void test_file_name_with_digit_prefix() {
        String result = FILE_NAME_CHECK.file_name_check("1example.txt");
        assertEquals("No", result);
    }

    // Returns 'No' for a file name with a substring before the dot that starts with a special character.
    @Test
    public void test_file_name_with_special_character() {
        String result = FILE_NAME_CHECK.file_name_check("#example.txt");
        assertEquals("No", result);
    }
}