package CHOOSE_NUM;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class ChooseNumTest {


    // The function returns the biggest even integer number in the range [x, y] inclusive.
    @Test
    public void test_biggest_even_number() {
        int result = CHOOSE_NUM.choose_num(12, 15);
        assertEquals(14, result);
    }

    // When x is greater than y, the function returns -1.
    @Test
    public void test_x_greater_than_y() {
        int result = CHOOSE_NUM.choose_num(13, 12);
        assertEquals(-1, result);
    }

    // When x and y are the same odd integer number, the function returns -1.
    @Test
    public void test_same_odd_number() {
        int result = CHOOSE_NUM.choose_num(13, 13);
        assertEquals(-1, result);
    }
}