package FILTER_BY_SUBSTRING;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.List;

public class FilterBySubstringTest {


    // The method returns an empty list when the input list is empty.
    @Test
    public void test_empty_list() {
        List<String> strings = new ArrayList<>();
        String substring = "abc";
        List<String> result = FILTER_BY_SUBSTRING.filter_by_substring(strings, substring);
        assertTrue(result.isEmpty());
    }

    // The method returns an empty list when none of the strings in the input list contain the given substring.
    @Test
    public void test_no_matching_strings() {
        List<String> strings = new ArrayList<>();
        strings.add("def");
        strings.add("ghi");
        strings.add("jkl");
        String substring = "abc";
        List<String> result = FILTER_BY_SUBSTRING.filter_by_substring(strings, substring);
        assertTrue(result.isEmpty());
    }

    // The method returns an empty list when the input list is null.
/*     @Test
    public void test_empty_list() {
        List<String> strings = null;
        String substring = "abc";
        List<String> result = FILTER_BY_SUBSTRING.filter_by_substring(strings, substring);
        assertTrue(result.isEmpty());
    } */
}