package ANTI_SHUFFLE;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class AntiShuffleTest {


    // It returns the same string if the input string has only one word.
    @Test
    public void test_same_string_one_word() {
        String input = "Hello";
        String expected = "Hello";
        String actual = ANTI_SHUFFLE.anti_shuffle(input);
        assertEquals(expected, actual);
    }

    // It returns an empty string if the input string is empty.
    @Test
    public void test_empty_string() {
        String input = "";
        String expected = "";
        String actual = ANTI_SHUFFLE.anti_shuffle(input);
        assertEquals(expected, actual);
    }

    // It returns a string with only spaces if the input string has only spaces.
    @Test
    public void test_returns_string_with_only_spaces_if_input_string_has_only_spaces() {
        String input = "     ";
        String expected = "     ";
        String actual = ANTI_SHUFFLE.anti_shuffle(input);
        assertEquals(expected, actual);
    }
}