package FACTORIAL;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.ArrayList;

public class FACTORIALTest {


    // Returns a list of size n, where each element is either the factorial of i (if i is even) or the sum of numbers from 1 to i (if i is odd).
    @Test
    public void test_factorial() {
        ArrayList<Integer> expected = new ArrayList<>();
        expected.add(1);
        expected.add(2);
        expected.add(6);
        expected.add(24);
        expected.add(15);
    
        ArrayList<Integer> result = FACTORIAL.factorial(5);
    
        assertEquals(expected, result);
    }

    // Returns an empty list if n is negative.
    @Test
    public void test_negative_n() {
        ArrayList<Integer> expected = new ArrayList<>();
    
        ArrayList<Integer> result = FACTORIAL.factorial(-5);
    
        assertEquals(expected, result);
    }

/*     // Returns an empty list if n is null.
    @Test
    public void test_returns_empty_list_if_n_is_null() {
        ArrayList<Integer> expected = new ArrayList<>();
        ArrayList<Integer> result = FACTORIAL.factorial(null);
        assertEquals(expected, result);
    } */
}