package DERIVATIVE;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.ArrayList;
import java.util.List;

public class DERIVATIVETest {


    // Test with a polynomial of degree 0
    @Test
    public void test_polynomial_degree_0() {
        List<Integer> xs = new ArrayList<>();
        xs.add(5);
        List<Integer> expected = new ArrayList<>();
        expected.add(0);
        List<Integer> result = DERIVATIVE.derivative(xs);
        assertEquals(expected, result);
    }

    // Test with an empty list
    @Test
    public void test_empty_list() {
        List<Integer> xs = new ArrayList<>();
        List<Integer> expected = new ArrayList<>();
        List<Integer> result = DERIVATIVE.derivative(xs);
        assertEquals(expected, result);
    }

/*     // Test with a list containing only one coefficient
    @Test
    public void test_polynomial_degree_0() {
        List<Integer> xs = new ArrayList<>();
        xs.add(5);
        List<Integer> expected = new ArrayList<>();
        expected.add(0);
        List<Integer> result = DERIVATIVE.derivative(xs);
        assertEquals(expected, result);
    } */
}