package COMPARE_ONE;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class CompareOneTest {


    // Returns the larger variable in its given variable type
    @Test
    public void test_returns_larger_variable() {
        Object result = COMPARE_ONE.compare_one(1, 2.5);
        assertEquals(2.5, result);
    
        result = COMPARE_ONE.compare_one(1, "2,3");
        assertEquals("2,3", result);
    
        result = COMPARE_ONE.compare_one("5,1", "6");
        assertEquals("6", result);
    
        result = COMPARE_ONE.compare_one("1", 1);
        assertNull(result);
    }

    // Handles null input for both parameters
    @Test
    public void test_handles_null_input() {
        Object result = COMPARE_ONE.compare_one(null, null);
        assertNull(result);
    
        result = COMPARE_ONE.compare_one(null, 2.5);
        assertEquals(2.5, result);
    
        result = COMPARE_ONE.compare_one("5,1", null);
        assertEquals("5,1", result);
    }

    // Handles empty string input for both parameters
    @Test
    public void test_handles_empty_string_input() {
        Object result = COMPARE_ONE.compare_one("", "");
        assertNull(result);

        result = COMPARE_ONE.compare_one("", 2.5);
        assertNull(result);

        result = COMPARE_ONE.compare_one(1, "");
        assertNull(result);
    }
}