package CIRCULAR_SHIFT;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class CircularShiftTest {


    // Should return the circular shifted string for a positive integer and a positive shift value
    @Test
    public void test_circular_shift_positive_integer_positive_shift() {
        String result = CIRCULAR_SHIFT.circular_shift(12, 1);
        assertEquals("21", result);
    }

    // Should return the original string for a positive integer and a shift value of 0
    @Test
    public void test_circular_shift_positive_integer_zero_shift() {
        String result = CIRCULAR_SHIFT.circular_shift(12, 0);
        assertEquals("12", result);
    }

    // Should return the original string for a negative integer and a shift value of 0
    @Test
    public void test_original_string_negative_integer_shift_0() {
        String result = CIRCULAR_SHIFT.circular_shift(-123, 0);
        assertEquals("-123", result);
    }
}