package ADD_ELEMENTS;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.ArrayList;

public class AddElementsTest {


    // Should return 0 if k is 0
    @Test
    public void test_return_zero_if_k_is_zero() {
        ArrayList<Integer> arr = new ArrayList<>();
        arr.add(111);
        arr.add(21);
        arr.add(3);
        arr.add(4000);
        arr.add(5);
        arr.add(6);
        arr.add(7);
        arr.add(8);
        arr.add(9);
    
        int k = 0;
    
        int result = ADD_ELEMENTS.add_elements(arr, k);
    
        assertEquals(0, result);
    }

    // Should handle an empty array
    @Test
    public void test_handle_empty_array() {
        ArrayList<Integer> arr = new ArrayList<>();
    
        int k = 4;
    
        int result = ADD_ELEMENTS.add_elements(arr, k);
    
        assertEquals(0, result);
    }

    // Should handle an array with only one element
    @Test
    public void test_handle_array_with_one_element() {
        ArrayList<Integer> arr = new ArrayList<>();
        arr.add(111);
        int k = 1;
        int result = ADD_ELEMENTS.add_elements(arr, k);
        assertEquals(111, result);
    }
}