package ALL_PREFIXES;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.List;

public class AllPrefixesTest {


    // Should return an empty list when given an empty string
    @Test
    public void test_empty_string() {
        List<String> result = ALL_PREFIXES.all_prefixes("");
        assertTrue(result.isEmpty());
    }

    // Should return an empty list when given a null string
    @Test
    public void test_null_string() {
        List<String> result = ALL_PREFIXES.all_prefixes(null);
        assertTrue(result.isEmpty());
    }

    // Should return an empty list when given a string with only spaces
    @Test
    public void test_empty_string_with_spaces() {
        List<String> result = ALL_PREFIXES.all_prefixes("     ");
        assertTrue(result.isEmpty());
    }
}