package COUNT_NUMS;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.ArrayList;

public class CountNumsTest {


    // The method returns 0 when the input list is empty.
    @Test
    public void test_empty_list() {
        ArrayList<Integer> arr = new ArrayList<>();
        int result = COUNT_NUMS.count_nums(arr);
        assertEquals(0, result);
    }

    // The method correctly handles the case where the input list contains only one integer.
    @Test
    public void test_single_integer() {
        ArrayList<Integer> arr = new ArrayList<>();
        arr.add(5);
        int result = COUNT_NUMS.count_nums(arr);
        assertEquals(1, result);
    }

    // The method correctly handles the case where the input list contains only negative integers.
    @Test
    public void test_only_negative_integers() {
        ArrayList<Integer> arr = new ArrayList<>();
        arr.add(-5);
        arr.add(-10);
        arr.add(-15);
        int result = COUNT_NUMS.count_nums(arr);
        assertEquals(3, result);
    }
}