package DECODE_CYCLIC;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class DecodeCyclicTest {


    // The method returns the expected output when given a string with a length that is a multiple of 3.
    @Test
    public void test_multiple_of_3_length_string() {
        String input = "abcxyz";
        String expectedOutput = "bcazyx";
    
        String actualOutput = DECODE_CYCLIC.decode_cyclic(input);
    
        assertEquals(expectedOutput, actualOutput);
    }

    // The method returns the expected output when given a null string.
    @Test
    public void test_null_string() {
        String input = null;
        String expectedOutput = null;

        String actualOutput = DECODE_CYCLIC.decode_cyclic(input);

        assertEquals(expectedOutput, actualOutput);
    }

    // The method returns the expected output when given a string with only twelve characters.
    @Test
    public void test_decode_cyclic_with_twelve_characters() {
        String input = "abcdefghijkl";
        String expectedOutput = "bcadefghiklj";

        String actualOutput = DECODE_CYCLIC.decode_cyclic(input);

        assertEquals(expectedOutput, actualOutput);
    }
}