package ADD_EVEN_AT_ODD;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class AddEvenAtOddTest {


    // The method returns 0 when the list has only odd elements.
    @Test
    public void test_returns_zero_when_list_has_only_odd_elements() {
        int[] lst = {1, 3, 5, 7};
        int result = ADD_EVEN_AT_ODD.add_even_at_odd(lst);
        assertEquals(0, result);
    }

    // The method throws a NullPointerException when the input list is null.
    @Test
    public void test_throws_NullPointerException_when_input_list_is_null() {
        int[] lst = null;
        assertThrows(NullPointerException.class, () -> ADD_EVEN_AT_ODD.add_even_at_odd(lst));
    }

    // The method returns 0 when the input list is empty.
    @Test
    public void test_returns_zero_when_list_is_empty() {
        int[] lst = {};
        int result = ADD_EVEN_AT_ODD.add_even_at_odd(lst);
        assertEquals(0, result);
    }
}