package CORRECT_BRACKETING;


// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class CorrectBracketingTest {


    // returns True for a single pair of brackets "<>"
    @Test
    public void test_returns_true_for_single_pair_of_brackets() {
        boolean result = CORRECT_BRACKETING.correct_bracketing("<>");
        assertTrue(result);
    }

    // returns False for a single opening bracket "<"
    @Test
    public void test_returns_false_for_single_opening_bracket() {
        boolean result = CORRECT_BRACKETING.correct_bracketing("<");
        assertFalse(result);
    }

    // returns False for a single closing bracket ">"
    @Test
    public void test_returns_false_for_single_closing_bracket() {
        boolean result = CORRECT_BRACKETING.correct_bracketing(">");
        assertFalse(result);
    }
}