package DIGIT_SUM;

// Generated by CodiumAI

import org.junit.Test;
import static org.junit.Assert.*;

public class DIGITSUMTest {

    // Should handle input strings with only one uppercase letter
    @Test
    public void test_handle_input_string_with_only_one_uppercase_letter() {
        int result = DIGIT_SUM.digit_sum("A");
        assertEquals(65, result);
    }

    // Should return 0 when given an empty string
    @Test
    public void test_empty_string() {
        int result = DIGIT_SUM.digit_sum("");
        assertEquals(0, result);
    }

    // Should handle input strings with only one lowercase letter
    @Test
    public void test_handle_single_lowercase_letter() {
        int result = DIGIT_SUM.digit_sum("a");
        assertEquals(0, result);
    }
}